name: flutterkeepgoing
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  # 事件总线  https://pub.dev/packages/event_bus
  event_bus: ^1.1.0
  # 数据存储 https://pub.dev/packages/shared_preferences
  shared_preferences: ^0.5.3+4
  # 加密散列函数 https://pub.dev/packages/crypto
  crypto: ^2.0.6
  # 网络请求 https://pub.dev/packages/dio
  dio: ^2.1.0
  # Image 扩展组件 https://pub.dev/packages/extended_image
  extended_image: ^0.5.5
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^1.1.1
  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^1.5.1
  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: 0.3.10+4
  # toast 插件 https://pub.dev/packages/oktoast#-readme-tab-
  oktoast: ^2.2.0
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^1.1.3
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: 0.2.6+1
  # RxDart是基于ReactiveX的Google Dart反应式函数式编程库 https://github.com/ReactiveX/rxdart
  rxdart: ^0.22.1+1
  # Flutter 轮播图 https://github.com/best-flutter/flutter_swiper
  flutter_swiper: ^1.1.6
  # 启动URL的插件 https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: 5.1.2
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^2.1.1+1
  # 图片缓存本地相册 https://pub.dev/packages/image_picker_saver#-installing-tab-
  image_picker_saver: ^0.3.0
  # 图片裁切 https://pub.dev/packages/image_cropper#-installing-tab-
  image_cropper: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter



# The following section is specific to Flutter.
flutter:
  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/home/
    - assets/images/home/2.0x/
    - assets/images/mycourise/
    - assets/images/mycourise/2.0x/
    - assets/images/mine/
    - assets/images/mine/2.0x/
    - assets/images/mine/3.0x/

    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
